import CategoricalBayesianNetworksProofs.Examples
import CategoricalBayesianNetworksProofs.CertificateExamples
import CategoricalBayesianNetworksProofs.LocalTables
import CategoricalBayesianNetworksProofs.CertificateJSON
